name: Security & Deploy

on:
  push:
    branches:
      - main

jobs:
  codeql:
    name: CodeQL SAST
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
      - uses: github/codeql-action/analyze@v2

  secret-scan:
    name: Secret scanning with Gitleaks
    needs: codeql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: --path=. --exit-code=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to Elastic Beanstalk
    needs: secret-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            eu-north-1

      - name: Bootstrap EB directory
        run: |
          eb init damage-report-app \
             --region eu-north-1 \
             --platform "python-3.11" \
             --no-interactive
          eb use damage-env

      - name: Deploy
        run: eb deploy damage-env